### PR TITLE
Summary grammar fix

### PR DESCRIPTION
**Pull request by languitar**

### CODE REVIEW

**Comment by i8enn** [comment]
@languitar Oh... Thanks! I'm not knowledge in English, and I quite often use google translator - sometimes there are such cases... 

Thanks again for correcting the mistakes. If not difficult, you could fix a similar error in [setup.py](https://github.com/i8enn/pydantic-odm/blob/master/setup.py#L38) I will accept this PR.

**Review by i8enn — CHANGES_REQUESTED** [review]
If not difficult, you could fix a similar error in [setup.py](https://github.com/i8enn/pydantic-odm/blob/master/setup.py#L38) and I will accept this PR.

**Comment by languitar** [comment]
No problem. It's included now.

Just as an alternative: for the languages I speak [DeepL](https://www.deepl.com/translator) gives much better results.

**Review by i8enn — APPROVED** [review]

**Comment by i8enn** [comment]
@languitar Perfect! Thank you very much for your contribution to the repository and the useful link to the translator service.

By the way, the answer I write using this service.The only thing missing is a quick change of language (Russian -> English and English -> Russian) like Google Translate hotkey `CTRL+SHIFT+S`.

**Pull request merged**
